/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all employees */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all employees */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new employee */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeCreate"];
                };
            };
            responses: {
                /** @description Employee created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/tg/{tgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an employee by Telegram ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Telegram ID */
                    tgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Employee details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"];
                    };
                };
                /** @description Employee not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an employee by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Employee ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Employee details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"];
                    };
                };
                /** @description Employee not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Update an employee by ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Employee ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeUpdate"];
                };
            };
            responses: {
                /** @description Employee updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"];
                    };
                };
                /** @description Employee not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an employee by ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Employee ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Employee deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Employee not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harvests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all harvests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all harvests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Harvest"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new harvest */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HarvestCreate"];
                };
            };
            responses: {
                /** @description Harvest created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Harvest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harvests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a harvest by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Harvest ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Harvest details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Harvest"];
                    };
                };
                /** @description Harvest not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Update a harvest by ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Harvest ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HarvestUpdate"];
                };
            };
            responses: {
                /** @description Harvest updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Harvest"];
                    };
                };
                /** @description Harvest not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a harvest by ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Harvest ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Harvest deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Harvest not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Harvest: {
            /** @description Unique identifier */
            id: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /** @description Harvest quantity */
            quantity?: number | null;
            /** @description Employee ID who logged the harvest */
            loggedBy: number;
        };
        HarvestCreate: {
            /** @description Harvest quantity */
            quantity?: number | null;
            /** @description Employee ID who logged the harvest */
            loggedBy: number;
        };
        HarvestUpdate: {
            /** @description Harvest quantity */
            quantity?: number | null;
            /** @description Employee ID who logged the harvest */
            loggedBy?: number;
        };
        Employee: {
            /** @description Unique identifier */
            id: number;
            /** @description Telegram ID */
            tgId?: string | null;
            /** @description Employee name */
            name: string;
        };
        EmployeeCreate: {
            /** @description Telegram ID */
            tgId?: string | null;
            /** @description Employee name */
            name: string;
        };
        EmployeeUpdate: {
            /** @description Telegram ID */
            tgId?: string | null;
            /** @description Employee name */
            name?: string;
        };
        Error: {
            /** @description Error message */
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
